kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-full-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-full-access
subjects:
- kind: Group
  namespace: web
  name: 1cb8148d-c6fc-4b2b-85f7-5fb925c71b00
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-view-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-view-access
subjects:
- kind: Group
  namespace: web
  name: 4eed623d-88b2-4419-8a05-f5807ceb2de9  