# This is a SecretProviderClass example using aad-pod-identity to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-podid
  namespace: api
spec:
  provider: azure
  secretObjects:
    - secretName: mssqlkv
      type: Opaque
      data:
      - key: SQL_USER
        objectName: SQLUSER
      - key: SQL_PASSWORD
        objectName: SQLPASSWORD
      - key: SQL_DBNAME
        objectName: SQLDBNAME
      - key: SQL_SERVER
        objectName: SQLSERVER

  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access keyvault
    keyvaultName: team1akshackkeyvault       # Set to the name of your Azure Key Vault instance
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLUSER
          objectType: secret             # object types: secret, key or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLDBNAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLSERVER
          objectType: secret
          objectVersion: ""
    tenantId: 31ac6e3e-689e-4190-ab43-9eec25323e3c                # The tenant ID of the Azure Key Vault instance